# Generated by Django 5.2.7 on 2025-11-06 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único del evento (ej: nuevo_dispositivo)', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del evento', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del evento')),
                ('activo', models.BooleanField(default=True, help_text='¿Está activo este evento?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Evento Push',
                'verbose_name_plural': 'Tipos de Eventos Push',
                'db_table': 'telegram_event_types',
            },
        ),
        migrations.CreateModel(
            name='TelegramNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(help_text='ID de usuario que recibió la notificación')),
                ('mensaje', models.TextField(help_text='Contenido del mensaje enviado')),
                ('enviado', models.BooleanField(default=False, help_text='¿Se envió correctamente?')),
                ('error', models.TextField(blank=True, help_text='Mensaje de error si falló', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales del evento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.ForeignKey(help_text='Tipo de evento', on_delete=django.db.models.deletion.CASCADE, to='push_telegram.telegrameventtype')),
            ],
            options={
                'verbose_name': 'Log de Notificación',
                'verbose_name_plural': 'Logs de Notificaciones',
                'db_table': 'telegram_notification_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(help_text='ID de usuario de Telegram (número)')),
                ('nombre_usuario', models.CharField(blank=True, help_text='Nombre del usuario (para referencia)', max_length=100)),
                ('activo', models.BooleanField(default=True, help_text='¿Está activa esta suscripción?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(help_text='Evento al que está suscrito', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='push_telegram.telegrameventtype')),
            ],
            options={
                'verbose_name': 'Suscripción Push',
                'verbose_name_plural': 'Suscripciones Push',
                'db_table': 'telegram_subscriptions',
                'unique_together': {('telegram_user_id', 'event_type')},
            },
        ),
    ]
