# Generated by Django 5.2.7 on 2025-11-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_telegram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Token único de autorización (UUID)', max_length=100, unique=True)),
                ('uid_dispositivo', models.CharField(help_text='UID del dispositivo asociado', max_length=255)),
                ('telegram_message_id', models.BigIntegerField(help_text='ID del mensaje de Telegram que generó esta autorización')),
                ('telegram_user_id', models.BigIntegerField(help_text='ID del usuario de Telegram que autorizó')),
                ('accion', models.CharField(default='activate_device', help_text='Acción autorizada (ej: activate_device, delete_device)', max_length=50)),
                ('usada', models.BooleanField(default=False, help_text='¿Se ha usado esta autorización?')),
                ('expirada', models.BooleanField(default=False, help_text='¿Ha expirado esta autorización?')),
                ('expira_en', models.DateTimeField(help_text='Fecha y hora de expiración')),
                ('usada_en', models.DateTimeField(blank=True, help_text='Fecha y hora en que se usó', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Autorización Temporal',
                'verbose_name_plural': 'Autorizaciones Temporales',
                'db_table': 'telegram_autorizaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
