# Generated by Django 5.2.7 on 2025-11-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_telegram', '0002_telegramautorizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramautorizacion',
            name='empresa',
            field=models.CharField(default='testTPV', help_text='Identificador de la empresa/instancia TPV', max_length=100),
        ),
    ]
