# Generated by Django on 2025-11-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_telegram', '0003_telegramautorizacion_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsubscription',
            name='filtros',
            field=models.JSONField(blank=True, default=dict, help_text="Filtros adicionales para la suscripción (ej: {'zonas': [1, 2, 3]} para vigilar zonas específicas)"),
        ),
    ]
