# Generated by Django 4.2.26 on 2025-11-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_telegram', '0004_telegramsubscription_filtros'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del usuario (ej: Valle, Admin, Camarero1)', max_length=100, unique=True)),
                ('telegram_user_id', models.BigIntegerField(help_text='ID de usuario de Telegram (número)', unique=True)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción o rol del usuario (opcional)', max_length=200)),
                ('activo', models.BooleanField(default=True, help_text='¿Está activo este usuario?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuario de Telegram',
                'verbose_name_plural': 'Usuarios de Telegram',
                'db_table': 'telegram_users',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='telegramautorizacion',
            name='accion',
            field=models.CharField(default='activate_device', help_text='Acción autorizada (ej: activate_device, delete_device, dispositivo_action para acciones genéricas)', max_length=50),
        ),
        migrations.AlterField(
            model_name='telegramsubscription',
            name='filtros',
            field=models.JSONField(blank=True, default=dict, help_text="Filtros adicionales para la suscripción (ej: {'zonas': [1, 2, 3]}, {'camareros': [1, 5]}, etc.)"),
        ),
    ]
