# Generated by Django 4.2.26 on 2025-11-19 22:22

from django.db import migrations


def limpiar_suscripciones(apps, schema_editor):
    """
    Borrar todas las suscripciones existentes para migración limpia
    """
    TelegramSubscription = apps.get_model('push_telegram', 'TelegramSubscription')
    TelegramSubscription.objects.all().delete()


def reverso(apps, schema_editor):
    """
    No hay nada que hacer en reverso
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('push_telegram', '0005_telegramuser_alter_telegramautorizacion_accion_and_more'),
    ]

    operations = [
        migrations.RunPython(limpiar_suscripciones, reverso),
    ]
