# Generated by Django 4.2.26 on 2025-11-19 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push_telegram', '0006_auto_20251119_2322'),
    ]

    operations = [
        # Agregar nuevo campo FK
        migrations.AddField(
            model_name='telegramsubscription',
            name='usuario',
            field=models.ForeignKey(
                help_text='Usuario de Telegram suscrito',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subscriptions',
                to='push_telegram.telegramuser',
                default=1  # Temporal, se eliminará con los campos antiguos
            ),
            preserve_default=False,
        ),
        
        # Remover campos antiguos
        migrations.RemoveField(
            model_name='telegramsubscription',
            name='telegram_user_id',
        ),
        migrations.RemoveField(
            model_name='telegramsubscription',
            name='nombre_usuario',
        ),
        
        # Establecer nuevo unique_together
        migrations.AlterUniqueTogether(
            name='telegramsubscription',
            unique_together={('usuario', 'event_type')},
        ),
    ]
