# Generated by Django 4.2.26 on 2025-11-28 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push_telegram', '0007_auto_20251119_2325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramAutorizacion',
        ),
    ]
