# Generated by Django 4.2.26 on 2025-11-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_telegram', '0007_auto_20251119_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramautorizacion',
            name='mensaje',
            field=models.TextField(blank=True, help_text='Mensaje original enviado (para poder editarlo manteniendo el contenido)', null=True),
        ),
    ]
