# Generated by Django 4.1 on 2022-09-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='uid_device',
            field=models.CharField(default='11f1a3c7-5fdc-4950-b800-594932c6add5', max_length=15),
        ),
    ]
