# Generated by Django 4.2.26 on 2025-11-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenCallbackMapping',
            fields=[
                ('token', models.CharField(help_text='Token único de la notificación', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('callback_url', models.URLField(help_text='URL completa del endpoint de callback en el TPV')),
                ('empresa', models.CharField(help_text='Identificador de la empresa/instancia TPV', max_length=100)),
                ('accion', models.CharField(help_text='Acción que ejecutará el callback (activate_device, etc)', max_length=50)),
                ('telegram_user_id', models.BigIntegerField(help_text='ID del usuario de Telegram')),
                ('telegram_message_id', models.BigIntegerField(blank=True, help_text='ID del mensaje enviado a Telegram', null=True)),
                ('uid_dispositivo', models.CharField(blank=True, help_text='UID del dispositivo (si aplica)', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales de contexto')),
                ('expira_en', models.DateTimeField(help_text='Fecha y hora de expiración del token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usada', models.BooleanField(default=False, help_text='¿Se ejecutó el callback?')),
                ('usada_en', models.DateTimeField(blank=True, help_text='Cuándo se ejecutó el callback', null=True)),
            ],
            options={
                'verbose_name': 'Mapeo Token-Callback',
                'verbose_name_plural': 'Mapeos Token-Callback',
                'db_table': 'webhook_token_callbacks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expira_en', 'usada'], name='webhook_tok_expira__f06fd7_idx'), models.Index(fields=['empresa', 'created_at'], name='webhook_tok_empresa_7c3958_idx')],
            },
        ),
    ]
