# Generated by Django 4.2.26 on 2025-11-09 12:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.URLField(help_text='URL del origen permitido (ej: https://tpvtest.valletpv.es)', unique=True)),
                ('description', models.CharField(blank=True, help_text='Descripción del origen', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='¿Está activo este origen?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Origen CORS Permitido',
                'verbose_name_plural': 'Orígenes CORS Permitidos',
                'db_table': 'webhook_allowed_origins',
                'ordering': ['origin'],
            },
        ),
        migrations.CreateModel(
            name='TelegramAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Token único de autorización (UUID)', max_length=100, unique=True)),
                ('uid_dispositivo', models.CharField(help_text='UID del dispositivo asociado', max_length=255)),
                ('telegram_message_id', models.BigIntegerField(help_text='ID del mensaje de Telegram que generó esta autorización')),
                ('telegram_user_id', models.BigIntegerField(help_text='ID del usuario de Telegram que autorizó')),
                ('accion', models.CharField(default='activate_device', help_text='Acción autorizada', max_length=50)),
                ('empresa', models.CharField(help_text='Identificador de la empresa/instancia TPV', max_length=100)),
                ('usada', models.BooleanField(default=False, help_text='¿Se ha usado esta autorización?')),
                ('expirada', models.BooleanField(default=False, help_text='¿Ha expirado esta autorización?')),
                ('expira_en', models.DateTimeField(help_text='Fecha y hora de expiración')),
                ('usada_en', models.DateTimeField(blank=True, help_text='Fecha y hora en que se usó', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Autorización Temporal',
                'verbose_name_plural': 'Autorizaciones Temporales',
                'db_table': 'webhook_telegram_autorizaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TPVInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre identificativo del TPV', max_length=200)),
                ('api_key', models.CharField(help_text='Clave API para autenticación', max_length=255, unique=True)),
                ('endpoint_url', models.URLField(help_text='URL del servidor TPV para enviar instrucciones')),
                ('is_active', models.BooleanField(default=True)),
                ('max_users', models.IntegerField(default=100, help_text='Máximo de usuarios que puede manejar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, help_text='Última conexión del TPV', null=True)),
                ('version', models.CharField(blank=True, help_text='Versión del software TPV', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadatos adicionales del TPV')),
            ],
            options={
                'verbose_name': 'Instancia TPV',
                'verbose_name_plural': 'Instancias TPV',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(help_text='ID de usuario de Telegram', unique=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('language_code', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tpv_instance', models.ForeignKey(help_text='Instancia TPV asignada a este usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='webhook.tpvinstance')),
            ],
            options={
                'verbose_name': 'Usuario Telegram',
                'verbose_name_plural': 'Usuarios Telegram',
                'ordering': ['-last_interaction'],
            },
        ),
        migrations.CreateModel(
            name='PushMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('photo', 'Foto'), ('document', 'Documento'), ('location', 'Ubicación')], default='text', max_length=50)),
                ('text', models.TextField(blank=True, help_text='Texto del mensaje')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Datos adicionales (URL imagen, etc)')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_messages', to='webhook.telegramuser')),
                ('tpv_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_messages', to='webhook.tpvinstance')),
            ],
            options={
                'verbose_name': 'Mensaje Push',
                'verbose_name_plural': 'Mensajes Push',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='webhook_pus_status_205d71_idx'), models.Index(fields=['tpv_instance', 'status'], name='webhook_pus_tpv_ins_92d4a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command', models.CharField(help_text='Comando o acción a ejecutar', max_length=100)),
                ('payload', models.JSONField(default=dict, help_text='Datos adicionales de la instrucción')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('priority', models.IntegerField(default=5, help_text='Prioridad (1=alta, 10=baja)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración', null=True)),
                ('response', models.JSONField(blank=True, help_text='Respuesta del TPV', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='webhook.telegramuser')),
                ('tpv_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='webhook.tpvinstance')),
            ],
            options={
                'verbose_name': 'Instrucción',
                'verbose_name_plural': 'Instrucciones',
                'ordering': ['priority', '-created_at'],
                'indexes': [models.Index(fields=['tpv_instance', 'status'], name='webhook_ins_tpv_ins_75836d_idx'), models.Index(fields=['status', 'created_at'], name='webhook_ins_status_163464_idx')],
            },
        ),
    ]
