export const GET_REQUEST = 'GET_REQUEST'
export const ERROR_REQUEST = 'ERROR_REQUEST'
export const GET_TOKEN = 'GET_TOKEN'
export const GET_LISTADOS = 'GET_LISTADOS'
export const GET_LISTADOS_COMPUESTOS = "GET_LISTADOS_COMPUESTOS"
export const GET_TECLADOS = "GET_TECLADOS"
