# Generated by Django 4.1 on 2023-07-02 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arqueocaja',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cambio', models.FloatField(db_column='Cambio')),
                ('descuadre', models.FloatField(db_column='Descuadre')),
            ],
            options={
                'db_table': 'arqueocaja',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Camareros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=False)),
                ('autorizado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(default='', max_length=200)),
                ('permisos', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'camareros',
                'ordering': ['apellidos'],
            },
        ),
        migrations.CreateModel(
            name='Cierrecaja',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ticketcom', models.IntegerField(db_column='TicketCom')),
                ('ticketfinal', models.IntegerField(db_column='TicketFinal')),
                ('fecha', models.DateField(db_column='Fecha')),
                ('hora', models.CharField(db_column='Hora', max_length=5)),
            ],
            options={
                'db_table': 'cierrecaja',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ComposicionTeclas',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('compuesto_por', models.CharField(max_length=300)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'composicion_teclas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Familias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('compuesto_por', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField(default=0)),
                ('color', models.CharField(default='#FFC0CB', max_length=11)),
            ],
            options={
                'db_table': 'familias',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Infmesa',
            fields=[
                ('uid', models.CharField(db_column='UID', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('hora', models.CharField(db_column='Hora', max_length=5)),
                ('numcopias', models.IntegerField(db_column='NumCopias', default=0)),
                ('camarero', models.ForeignKey(db_column='IDCam', on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.camareros')),
            ],
            options={
                'db_table': 'infmesa',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Lineaspedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('A', 'Anulado'), ('P', 'Pedido activo'), ('R', 'Regalo'), ('C', 'Linea cobrada'), ('M', 'Pertenece a promocion o grupo')], default='P', max_length=1)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descripcion', models.CharField(default=None, max_length=400, null=True)),
                ('es_compuesta', models.BooleanField(default=False, verbose_name='Grupo o simple')),
                ('can_composicion', models.IntegerField(default=0, verbose_name='Cantidad de articulos que lo compone')),
                ('descripcion_t', models.CharField(blank=True, db_column='Descripcion_t', max_length=300, null=True, verbose_name='Descripción ticket')),
                ('infmesa', models.ForeignKey(db_column='UID', on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.infmesa')),
            ],
            options={
                'db_table': 'lineaspedido',
            },
        ),
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-orden'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Receptores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'receptores',
            },
        ),
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(default='#FFC0CB', max_length=11)),
                ('orden', models.IntegerField(default=0)),
                ('icono', models.FileField(blank=True, null=True, upload_to='iconos_secciones')),
            ],
            options={
                'db_table': 'secciones',
                'ordering': ['-orden'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('camarero_id', models.IntegerField(db_column='IDCam')),
                ('hora', models.CharField(db_column='Hora', max_length=5)),
                ('entrega', models.DecimalField(db_column='Entrega', decimal_places=2, max_digits=6)),
                ('uid', models.CharField(db_column='UID', max_length=100)),
                ('mesa', models.CharField(db_column='Mesa', max_length=40)),
                ('url_factura', models.CharField(default='', max_length=140)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('tarifa', models.IntegerField()),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'zonas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Ticketlineas',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('linea', models.ForeignKey(db_column='IDLinea', on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.lineaspedido')),
                ('ticket', models.ForeignKey(db_column='IDTicket', on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.ticket')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Teclas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('p1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('p2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('orden', models.IntegerField(blank=True, default=0)),
                ('tag', models.CharField(blank=True, default='', max_length=100)),
                ('descripcion_r', models.CharField(blank=True, max_length=300, null=True)),
                ('descripcion_t', models.CharField(blank=True, max_length=300, null=True)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.familias')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.teclas')),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.secciones')),
            ],
            options={
                'db_table': 'teclas',
                'ordering': ['-orden'],
            },
        ),
        migrations.CreateModel(
            name='Sugerencias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sugerencia', models.CharField(max_length=300)),
                ('orden', models.IntegerField(blank=True, default=0)),
                ('tecla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.teclas')),
            ],
            options={
                'db_table': 'sugerencias',
            },
        ),
        migrations.CreateModel(
            name='Servidos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('linea', models.ForeignKey(db_column='IDLinea', on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.lineaspedido')),
            ],
            options={
                'db_table': 'servidos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PeticionesAutoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=150)),
                ('instrucciones', models.CharField(max_length=300)),
                ('idautorizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.camareros')),
            ],
            options={
                'db_table': 'peticiones_autoria',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.CharField(max_length=5)),
                ('camarero_id', models.IntegerField()),
                ('uid_device', models.CharField(default='', max_length=150)),
                ('infmesa', models.ForeignKey(db_column='UID', on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.infmesa')),
            ],
            options={
                'db_table': 'pedidos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Mesasabiertas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('infmesa', models.ForeignKey(db_column='UID', on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.infmesa')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.mesas')),
            ],
            options={
                'db_table': 'mesasabiertas',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='mesas',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.zonas'),
        ),
        migrations.AddField(
            model_name='lineaspedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.pedidos'),
        ),
        migrations.AddField(
            model_name='lineaspedido',
            name='tecla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='valle_tpv.teclas'),
        ),
        migrations.CreateModel(
            name='LineasCompuestas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linea_compuesta', models.IntegerField()),
                ('composicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.composicionteclas')),
                ('linea_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.lineaspedido')),
            ],
            options={
                'db_table': 'lineas_compuestas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HorarioUsr',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('hora_ini', models.CharField(db_column='Hora_ini', max_length=5)),
                ('hora_fin', models.CharField(db_column='Hora_fin', max_length=5)),
                ('usurario', models.ForeignKey(db_column='IDUsr', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'horario_usr',
            },
        ),
        migrations.CreateModel(
            name='Historialnulos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.CharField(max_length=5)),
                ('motivo', models.CharField(max_length=200)),
                ('camarero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.camareros')),
                ('lineapedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.lineaspedido')),
            ],
            options={
                'db_table': 'historialnulos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMensajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=300)),
                ('hora', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('camarero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.camareros')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.receptores')),
            ],
            options={
                'db_table': 'historialmensajes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=100)),
                ('importe', models.DecimalField(db_column='Importe', decimal_places=2, max_digits=6)),
                ('arqueo', models.ForeignKey(db_column='IDArqueo', on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.arqueocaja')),
            ],
            options={
                'db_table': 'gastos',
            },
        ),
        migrations.AddField(
            model_name='familias',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.receptores'),
        ),
        migrations.CreateModel(
            name='Efectivo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('can', models.IntegerField(db_column='Can')),
                ('moneda', models.DecimalField(db_column='Moneda', decimal_places=2, max_digits=5)),
                ('arqueo', models.ForeignKey(db_column='IDArqueo', on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.arqueocaja')),
            ],
            options={
                'db_table': 'efectivo',
            },
        ),
        migrations.AddField(
            model_name='composicionteclas',
            name='tecla',
            field=models.ForeignKey(db_column='IDTecla', on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.teclas'),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='cierre',
            field=models.ForeignKey(db_column='IDCierre', on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.cierrecaja'),
        ),
    ]
