# Generated by Django 4.1 on 2023-07-12 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valle_tpv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familias',
            name='receptor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='valle_tpv.receptores'),
        ),
        migrations.AlterField(
            model_name='secciones',
            name='icono',
            field=models.FileField(blank=True, null=True, upload_to='iconos_secciones/'),
        ),
        migrations.AlterField(
            model_name='teclas',
            name='familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='valle_tpv.familias'),
        ),
        migrations.AlterField(
            model_name='teclas',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='valle_tpv.teclas'),
        ),
        migrations.AlterField(
            model_name='teclas',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='valle_tpv.secciones'),
        ),
    ]
