# Generated by Django 4.1 on 2023-07-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valle_tpv', '0002_alter_familias_receptor_alter_secciones_icono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('razonsocial', models.CharField(default='', max_length=100)),
                ('cif', models.CharField(default='', max_length=20)),
                ('direccion', models.CharField(default='', max_length=100)),
                ('cp', models.CharField(default='', max_length=10)),
                ('localidad', models.CharField(default='', max_length=100)),
                ('provincia', models.CharField(default='', max_length=100)),
                ('telefono', models.CharField(default='', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('logo_small', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('email', models.CharField(max_length=100)),
                ('iva', models.FloatField(default=10)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
                'ordering': ['-id'],
            },
        ),
    ]
