# Generated by Django 4.1 on 2023-07-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valle_tpv', '0003_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='teclas',
            name='incremento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo_small',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='teclas',
            name='p1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='teclas',
            name='p2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
