# Generated by Django 4.1 on 2023-07-15 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('valle_tpv', '0004_teclas_incremento_alter_empresa_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('UID', models.CharField(default='', max_length=100)),
                ('codigo', models.CharField(default='', max_length=6)),
                ('descripcion', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'dispositivos',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='camarero_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='camarero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='valle_tpv.camareros'),
        ),
        migrations.AlterField(
            model_name='arqueocaja',
            name='cambio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='arqueocaja',
            name='cierre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.cierrecaja'),
        ),
        migrations.AlterField(
            model_name='arqueocaja',
            name='descuadre',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='arqueocaja',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='hora',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='ticketcom',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='ticketfinal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='efectivo',
            name='arqueo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.arqueocaja'),
        ),
        migrations.AlterField(
            model_name='efectivo',
            name='can',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='efectivo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='efectivo',
            name='moneda',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='arqueo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.arqueocaja'),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='horariousr',
            name='hora_fin',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='horariousr',
            name='hora_ini',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='horariousr',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='horariousr',
            name='usurario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='entrega',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='hora',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='mesa',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='uid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketlineas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticketlineas',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.lineaspedido'),
        ),
        migrations.AlterField(
            model_name='ticketlineas',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valle_tpv.ticket'),
        ),
    ]
