# Generated by Django 4.1 on 2023-08-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valle_tpv', '0005_dispositivos_remove_ticket_camarero_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secciones',
            name='color',
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='puede_enviar',
            field=models.BooleanField(default=True),
        ),
    ]
