# Generated by Django 4.1 on 2023-09-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valle_tpv', '0006_remove_secciones_color_dispositivos_puede_enviar'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptores',
            name='isTicket',
            field=models.BooleanField(default=False),
        ),
    ]
