# Generated by Django 4.1 on 2023-09-05 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('valle_tpv', '0007_receptores_isticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptores',
            name='nom_impresora',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
