# Generated by Django 5.1.1 on 2025-06-13 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camareros',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('apellidos', models.CharField(db_column='Apellidos', max_length=100)),
                ('email', models.CharField(db_column='Email', max_length=50, null=True)),
                ('pass_field', models.CharField(db_column='Pass', max_length=100, null=True)),
                ('activo', models.IntegerField(db_column='Activo', default=1)),
                ('autorizado', models.IntegerField(db_column='Autorizado', default=1)),
                ('permisos', models.CharField(db_column='Permisos', default='', max_length=150, null=True)),
            ],
            options={
                'db_table': 'camareros',
                'ordering': ['apellidos'],
            },
        ),
        migrations.CreateModel(
            name='Cierrecaja',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ticketcom', models.IntegerField(db_column='TicketCom')),
                ('ticketfinal', models.IntegerField(db_column='TicketFinal')),
                ('fecha', models.CharField(db_column='Fecha', max_length=10)),
                ('hora', models.CharField(db_column='Hora', max_length=5)),
            ],
            options={
                'db_table': 'cierrecaja',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ComposicionTeclas',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('composicion', models.CharField(max_length=300)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'composicionteclas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dispositivos',
            },
        ),
        migrations.CreateModel(
            name='IconChoices',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('orden', models.IntegerField(db_column='Orden', default=0)),
            ],
            options={
                'db_table': 'mesas',
                'ordering': ['-orden'],
            },
        ),
        migrations.CreateModel(
            name='PermisosChoices',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receptores',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=40)),
                ('nomimp', models.CharField(db_column='nomImp', max_length=40)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
                ('descripcion', models.CharField(db_column='Descripcion', default='', max_length=200)),
            ],
            options={
                'db_table': 'receptores',
            },
        ),
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('rgb', models.CharField(db_column='RGB', max_length=11, verbose_name='Color')),
            ],
            options={
                'db_table': 'secciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SeccionesCom',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=11)),
                ('icono', models.CharField(choices=[('bar', 'Bar'), ('bocadillo', 'Bocadillo'), ('carne', 'Carne'), ('cocktel', 'Cocktel'), ('copa_con_limon', 'Copa con rodaja de limon'), ('copa_vino', 'Copa de vino'), ('cubalibre', 'Cubalibre'), ('donut', 'Donut'), ('jarra_cerveza', 'Jarra de cerveza'), ('llevar', 'Icono para llevar'), ('magdalena', 'Magdalena'), ('menu', 'Menu'), ('pescado', 'Pescado'), ('pincho', 'Pincho'), ('pizza', 'Pizza'), ('plato', 'Plato humeante'), ('plato_combinado', 'Plato combinado'), ('sopa', 'Plato sopa'), ('sopa_cuchara', 'Plato sopa con cuchara'), ('tarta', 'Tarta'), ('taza_cafe', 'Taza cafe'), ('aperitivo', 'Plato doritos')], db_column='Icono', default='bar', max_length=15)),
            ],
            options={
                'db_table': 'secciones_com',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fecha', models.CharField(db_column='Fecha', max_length=10)),
                ('camarero_id', models.IntegerField(db_column='IDCam')),
                ('hora', models.CharField(db_column='Hora', max_length=5)),
                ('entrega', models.DecimalField(db_column='Entrega', decimal_places=2, max_digits=6)),
                ('uid', models.CharField(db_column='UID', max_length=100)),
                ('mesa', models.CharField(db_column='Mesa', max_length=40)),
                ('url_factura', models.CharField(default='', max_length=140)),
                ('recibo_tarjeta', models.TextField(default='')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50, unique=True)),
                ('tarifa', models.IntegerField(db_column='Tarifa')),
                ('rgb', models.CharField(db_column='RGB', max_length=50, verbose_name='Color')),
            ],
            options={
                'db_table': 'zonas',
            },
        ),
        migrations.CreateModel(
            name='Arqueocaja',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cambio', models.FloatField(db_column='Cambio')),
                ('descuadre', models.FloatField(db_column='Descuadre')),
                ('stacke', models.FloatField(db_column='Stacke')),
                ('cambio_real', models.FloatField(db_column='CambioReal', default=0)),
                ('cierre', models.ForeignKey(db_column='IDCierre', on_delete=django.db.models.deletion.CASCADE, to='gestion.cierrecaja')),
            ],
            options={
                'db_table': 'arqueocaja',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Efectivo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('can', models.IntegerField(db_column='Can')),
                ('moneda', models.DecimalField(db_column='Moneda', decimal_places=2, max_digits=10)),
                ('arqueo', models.ForeignKey(db_column='IDArqueo', on_delete=django.db.models.deletion.CASCADE, to='gestion.arqueocaja')),
            ],
            options={
                'db_table': 'efectivo',
            },
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=100)),
                ('importe', models.DecimalField(db_column='Importe', decimal_places=2, max_digits=6)),
                ('arqueo', models.ForeignKey(db_column='IDArqueo', on_delete=django.db.models.deletion.CASCADE, to='gestion.arqueocaja')),
            ],
            options={
                'db_table': 'gastos',
            },
        ),
        migrations.CreateModel(
            name='HorarioUsr',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('hora_ini', models.CharField(db_column='Hora_ini', max_length=5)),
                ('hora_fin', models.CharField(db_column='Hora_fin', max_length=5)),
                ('usurario', models.ForeignKey(db_column='IDUsr', on_delete=django.db.models.deletion.CASCADE, related_name='horariousr', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'horariousr',
            },
        ),
        migrations.CreateModel(
            name='Infmesa',
            fields=[
                ('id', models.CharField(db_column='UID', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('fecha', models.CharField(db_column='Fecha', max_length=10)),
                ('hora', models.CharField(db_column='Hora', max_length=5)),
                ('numcopias', models.IntegerField(db_column='NumCopias', default=0)),
                ('camarero', models.ForeignKey(db_column='IDCam', on_delete=django.db.models.deletion.CASCADE, to='gestion.camareros')),
            ],
            options={
                'db_table': 'infmesa',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Lineaspedido',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('idart', models.IntegerField(db_column='IDArt')),
                ('estado', models.CharField(choices=[('A', 'Anulado'), ('P', 'Pedido activo'), ('R', 'Regalo'), ('C', 'Linea cobrada'), ('M', 'Pertenece a promocion o grupo')], db_column='Estado', default='P', max_length=1)),
                ('precio', models.DecimalField(db_column='Precio', decimal_places=2, max_digits=6)),
                ('descripcion', models.CharField(db_column='Descripcion', default=None, max_length=400, null=True)),
                ('es_compuesta', models.BooleanField(default=False, verbose_name='Grupo o simple')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad de articulos que lo compone')),
                ('descripcion_t', models.CharField(blank=True, db_column='Descripcion_t', max_length=300, null=True, verbose_name='Descripción ticket')),
                ('infmesa', models.ForeignKey(db_column='UID', on_delete=django.db.models.deletion.CASCADE, to='gestion.infmesa')),
            ],
            options={
                'db_table': 'lineaspedido',
            },
        ),
        migrations.CreateModel(
            name='LineasCompuestas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea_compuesta', models.IntegerField()),
                ('composicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.composicionteclas')),
                ('linea_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.lineaspedido')),
            ],
        ),
        migrations.CreateModel(
            name='Historialnulos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('hora', models.CharField(db_column='Hora', max_length=5)),
                ('motivo', models.CharField(db_column='Motivo', max_length=200)),
                ('camarero', models.ForeignKey(db_column='IDCam', on_delete=django.db.models.deletion.CASCADE, to='gestion.camareros')),
                ('lineapedido', models.ForeignKey(db_column='IDLPedido', on_delete=django.db.models.deletion.CASCADE, to='gestion.lineaspedido')),
            ],
            options={
                'db_table': 'historialnulos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Mesasabiertas',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('infmesa', models.ForeignKey(db_column='UID', on_delete=django.db.models.deletion.CASCADE, to='gestion.infmesa')),
                ('mesa', models.ForeignKey(db_column='IDMesa', on_delete=django.db.models.deletion.CASCADE, to='gestion.mesas')),
            ],
            options={
                'db_table': 'mesasabiertas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('hora', models.CharField(db_column='Hora', max_length=5)),
                ('camarero_id', models.IntegerField(db_column='IDCam')),
                ('uid_device', models.CharField(default='589274e0-4ae3-4008-a00b-ec7a19d74d01', max_length=150)),
                ('infmesa', models.ForeignKey(db_column='UID', on_delete=django.db.models.deletion.CASCADE, to='gestion.infmesa')),
            ],
            options={
                'db_table': 'pedidos',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='lineaspedido',
            name='pedido',
            field=models.ForeignKey(db_column='IDPedido', on_delete=django.db.models.deletion.CASCADE, to='gestion.pedidos'),
        ),
        migrations.CreateModel(
            name='PeticionesAutoria',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=150)),
                ('instrucciones', models.CharField(max_length=300)),
                ('idautorizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.camareros')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMensajes',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=300)),
                ('hora', models.CharField(max_length=10)),
                ('fecha', models.CharField(max_length=10)),
                ('camarero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.camareros')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.receptores')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Familias',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=40)),
                ('composicion', models.CharField(db_column='Tipo', max_length=150)),
                ('cantidad', models.IntegerField(blank=True, db_column='NumTapas', default=0, null=True, verbose_name='Numero de tapas')),
                ('receptor', models.ForeignKey(db_column='IDReceptor', on_delete=django.db.models.deletion.CASCADE, to='gestion.receptores')),
            ],
            options={
                'db_table': 'familias',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Servidos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('linea', models.ForeignKey(db_column='IDLinea', on_delete=django.db.models.deletion.CASCADE, to='gestion.lineaspedido')),
            ],
            options={
                'db_table': 'servidos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Teclas',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('p1', models.DecimalField(db_column='P1', decimal_places=2, default=0.0, help_text='Precio  (Tarifa 1)', max_digits=6)),
                ('p2', models.DecimalField(db_column='P2', decimal_places=2, default=0.0, help_text='Precio (Tarifa 2)', max_digits=6)),
                ('tag', models.CharField(blank=True, db_column='Tag', default='', max_length=100)),
                ('descripcion_r', models.CharField(blank=True, db_column='Descripcion_r', max_length=300, null=True, verbose_name='Descripción recepción')),
                ('descripcion_t', models.CharField(blank=True, db_column='Descripcion_t', max_length=300, null=True, verbose_name='Descripción ticket')),
                ('tipo', models.CharField(choices=[('SP', 'SIMPLE'), ('CM', 'COMPUESTA')], default='SP', help_text='Tipo de tecla: Simple o Compuesta', max_length=2)),
                ('familia', models.ForeignKey(db_column='IDFamilia', on_delete=django.db.models.deletion.CASCADE, to='gestion.familias')),
                ('parent_tecla', models.ForeignKey(blank=True, db_column='IDParentTecla', help_text='Tecla padre si esta tecla es un modificador (antes Subtecla)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subteclas', to='gestion.teclas')),
            ],
            options={
                'db_table': 'teclas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sugerencias',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sugerencia', models.CharField(db_column='Sugerencia', max_length=300)),
                ('incremento', models.DecimalField(db_column='Incremento', decimal_places=2, default=0.0, max_digits=6)),
                ('tecla', models.ForeignKey(db_column='IDTecla', default=-1, on_delete=django.db.models.deletion.CASCADE, to='gestion.teclas')),
            ],
            options={
                'db_table': 'sugerencias',
            },
        ),
        migrations.AddField(
            model_name='lineaspedido',
            name='tecla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.teclas'),
        ),
        migrations.AddField(
            model_name='composicionteclas',
            name='tecla',
            field=models.ForeignKey(db_column='IDTecla', on_delete=django.db.models.deletion.CASCADE, to='gestion.teclas'),
        ),
        migrations.CreateModel(
            name='TeclasAgotadas',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fecha', models.CharField(db_column='Fecha', max_length=10)),
                ('tecla', models.ForeignKey(db_column='IDTecla', on_delete=django.db.models.deletion.CASCADE, to='gestion.teclas')),
            ],
            options={
                'db_table': 'teclasagotadas',
            },
        ),
        migrations.CreateModel(
            name='Teclascom',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('orden', models.IntegerField(db_column='Orden', default=0)),
                ('seccion', models.ForeignKey(db_column='IDSeccion', on_delete=django.db.models.deletion.CASCADE, to='gestion.seccionescom')),
                ('tecla', models.ForeignKey(db_column='IDTecla', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.teclas')),
            ],
            options={
                'db_table': 'teclascom',
                'ordering': ['-orden'],
            },
        ),
        migrations.CreateModel(
            name='Teclaseccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.ForeignKey(db_column='IDSeccion', on_delete=django.db.models.deletion.CASCADE, to='gestion.secciones')),
                ('tecla', models.ForeignKey(db_column='IDTecla', on_delete=django.db.models.deletion.CASCADE, to='gestion.teclas')),
            ],
            options={
                'db_table': 'teclaseccion',
            },
        ),
        migrations.CreateModel(
            name='Ticketlineas',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('linea', models.ForeignKey(db_column='IDLinea', on_delete=django.db.models.deletion.CASCADE, to='gestion.lineaspedido')),
                ('ticket', models.ForeignKey(db_column='IDTicket', on_delete=django.db.models.deletion.CASCADE, to='gestion.ticket')),
            ],
            options={
                'db_table': 'ticketlineas',
            },
        ),
        migrations.CreateModel(
            name='Mesaszona',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('mesa', models.ForeignKey(db_column='IDMesa', on_delete=django.db.models.deletion.CASCADE, to='gestion.mesas')),
                ('zona', models.ForeignKey(db_column='IDZona', on_delete=django.db.models.deletion.CASCADE, to='gestion.zonas')),
            ],
            options={
                'db_table': 'mesaszona',
            },
        ),
    ]
