# Generated by Django 4.0.3 on 2022-04-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secciones',
            name='color',
        ),
        migrations.AlterField(
            model_name='seccionescom',
            name='descuento',
            field=models.IntegerField(blank=True, db_column='Descuento', default='0', null=True),
        ),
    ]
