# Generated by Django 4.0.3 on 2022-05-07 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='mensaje',
        ),
        migrations.AlterField(
            model_name='seccionescom',
            name='icono',
            field=models.CharField(choices=[('bar', 'Bar'), ('bocadillo', 'Bocadillo'), ('carne', 'Carne'), ('cocktel', 'Cocktel'), ('copa_con_limon', 'Copa con rodaja de limon'), ('copa_vino', 'Copa de vino'), ('cubalibre', 'Cubalibre'), ('donut', 'Donut'), ('jarra_cerveza', 'Jarra de cerveza'), ('llevar', 'Icono para llevar'), ('magdalena', 'Magdalena'), ('menu', 'Menu'), ('pescado', 'Pescado'), ('pincho', 'Pincho'), ('pizza', 'Pizza'), ('plato', 'Plato humeante'), ('plato_combinado', 'Plato combinado'), ('sopa', 'Plato sopa'), ('sopa_cuchara', 'Plato sopa con cuchara'), ('tarta', 'Tarta'), ('taza_cafe', 'Taza cafe'), ('aperitivo', 'Plato doritos')], db_column='Icono', default='bar', max_length=15),
        ),
        migrations.CreateModel(
            name='HistorialMensajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=300)),
                ('camarero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.camareros')),
            ],
        ),
    ]
