# Generated by Django 3.0.3 on 2020-07-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camareros',
            name='nombre',
            field=models.CharField(db_column='Nombre', max_length=100),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='descripcion',
            field=models.CharField(db_column='Descripcion', max_length=100),
        ),
        migrations.AlterField(
            model_name='historialnulos',
            name='motivo',
            field=models.CharField(db_column='Motivo', max_length=200),
        ),
        migrations.AlterField(
            model_name='infmesa',
            name='ref',
            field=models.CharField(db_column='Ref', max_length=100),
        ),
        migrations.AlterField(
            model_name='lineaspedido',
            name='nombre',
            field=models.CharField(db_column='Nombre', max_length=400),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='mensaje',
            field=models.CharField(db_column='Mensaje', default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='subteclas',
            name='descripcion_r',
            field=models.CharField(blank=True, db_column='Descripcion_r', max_length=300, null=True, verbose_name='Descripción recepción'),
        ),
        migrations.AlterField(
            model_name='subteclas',
            name='descripcion_t',
            field=models.CharField(blank=True, db_column='Descripcion_t', max_length=300, null=True, verbose_name='Descripción ticket'),
        ),
        migrations.AlterField(
            model_name='subteclas',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teclas',
            name='descripcion_r',
            field=models.CharField(blank=True, db_column='Descripcion_r', max_length=300, null=True, verbose_name='Descripción recepción'),
        ),
        migrations.AlterField(
            model_name='teclas',
            name='descripcion_t',
            field=models.CharField(blank=True, db_column='Descripcion_t', max_length=300, null=True, verbose_name='Descripción ticket'),
        ),
        migrations.AlterField(
            model_name='teclas',
            name='nombre',
            field=models.CharField(db_column='Nombre', max_length=50),
        ),
        migrations.AlterField(
            model_name='teclas',
            name='tipo',
            field=models.CharField(choices=[('SP', 'SIMPLE'), ('ML', 'COMPUESTA'), ('GR', 'GRUPO')], default='SP', max_length=2),
        ),
    ]
