# Generated by Django 4.0.3 on 2022-05-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesas',
            name='nombre',
            field=models.CharField(db_column='Nombre', max_length=50),
        ),
        migrations.AlterField(
            model_name='mesas',
            name='orden',
            field=models.IntegerField(db_column='Orden', default=0),
        ),
        migrations.AlterField(
            model_name='secciones',
            name='orden',
            field=models.IntegerField(db_column='Orden', default=0),
        ),
        migrations.AlterField(
            model_name='teclascom',
            name='orden',
            field=models.IntegerField(db_column='Orden', default=0),
        ),
    ]
