# Generated by Django 4.0.3 on 2022-05-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineaspedido',
            name='es_compuesta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lineaspedido',
            name='estado',
            field=models.CharField(choices=[('A', 'Anulado'), ('P', 'Pedido activo'), ('R', 'Regalo, promocion o grupo'), ('C', 'Linea cobrada')], db_column='Estado', default='P', max_length=1),
        ),
    ]
