# Generated by Django 4.1.1 on 2024-09-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='uid_device',
            field=models.CharField(default='3cb56942-d75b-465e-9f5c-65f4d21059ce', max_length=150),
        ),
    ]
