# Generated by Django 5.1.1 on 2025-07-20 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IconChoices',
        ),
        migrations.AlterField(
            model_name='teclas',
            name='parent_tecla',
            field=models.ForeignKey(blank=True, db_column='IDParentTecla', help_text='Tecla padre si esta tecla es un modificador (antes Subtecla)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subteclas', to='gestion.teclas'),
        ),
        migrations.AlterField(
            model_name='teclascom',
            name='tecla',
            field=models.ForeignKey(db_column='IDTecla', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teclascomanda', to='gestion.teclas'),
        ),
        migrations.AlterField(
            model_name='teclaseccion',
            name='tecla',
            field=models.ForeignKey(db_column='IDTecla', on_delete=django.db.models.deletion.CASCADE, related_name='teclasecciones', to='gestion.teclas'),
        ),
    ]
