# Generated by Django 4.1 on 2023-05-02 00:02

from django.db import migrations, models

from datetime import date

def migrate_fecha(apps, schema_editor):
    modelos = ["cierrecaja", "historialmensajes", "infmesa", "ticket"]
    for m in modelos:
        MiModelo = apps.get_model('gestion', m)
        for obj in MiModelo.objects.all():

            if obj.fecha:
                try:
                    fecha_obj = date(*map(int, obj.fecha.split("/")))
                except:
                    fecha_obj = date(*map(int, obj.fecha.split("-")))
            else:
                fecha_obj = date.today()

            
            obj.fecha = fecha_obj
            obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_fecha, migrations.RunPython.noop),
        
        migrations.AlterField(
            model_name='cierrecaja',
            name='fecha',
            field=models.DateField(db_column='Fecha'),
        ),
        migrations.AlterField(
            model_name='historialmensajes',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='infmesa',
            name='fecha',
            field=models.DateField(db_column='Fecha'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha',
            field=models.DateField(db_column='Fecha'),
        ),
    ]
