# Generated by Django 4.0.3 on 2022-04-01 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeticionesAutoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=150)),
                ('instrucciones', models.CharField(max_length=300)),
                ('idautorizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.camareros')),
            ],
        ),
    ]
