# Generated by Django 5.1.1 on 2025-07-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_delete_iconchoices_alter_teclas_parent_tecla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teclas',
            name='orden',
            field=models.IntegerField(db_column='Orden', default=0, help_text='Orden de la tecla dentro de su familia'),
        ),
    ]
