# Generated by Django 4.0.3 on 2022-05-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_lineaspedido_es_compuesta_alter_lineaspedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineaspedido',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
