# Generated by Django 4.0.3 on 2022-05-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_mesas_nombre_alter_mesas_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmensajes',
            name='fecha',
            field=models.CharField(default='', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialmensajes',
            name='hora',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
