# Generated by Django 4.0.3 on 2022-05-07 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_pedidos_mensaje_alter_seccionescom_icono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmensajes',
            name='receptor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.receptores'),
            preserve_default=False,
        ),
    ]
