# Generated by Django 5.1.1 on 2025-09-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_teclas_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineaspedido',
            name='id_local',
            field=models.BigIntegerField(db_column='IDLocal', null=True),
        ),
    ]
