# Generated by Django 4.0.3 on 2022-04-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_seccionescom_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccionescom',
            name='icono',
            field=models.CharField(choices=[('bar', 'Bar'), ('bocadillo', 'Bocadillo'), ('carne', 'Carne'), ('cocktel', 'Cocktel'), ('copa_con_limon', 'Copa con rodaja de limon'), ('copa_vino', 'Copa de vino'), ('cubalibre', 'Cubalibre'), ('donut', 'Donut'), ('jarra_cerveza', 'Jarra de cerveza'), ('llevar', 'Icono para llevar'), ('magdalena', 'Magdalena'), ('menu', 'Menu'), ('pescado', 'Pescado'), ('pincho', 'Pincho'), ('pizza', 'Pizza'), ('plato', 'Plato humeante'), ('plato_combinado', 'Plato combinado'), ('sopa', 'Plato sopa'), ('sopa_cuchara', 'Plato sopa con cuchara'), ('tarta', 'Tarta'), ('taza_cafe', 'Taza cafe')], db_column='Icono', default='bar', max_length=15),
        ),
    ]
