# Generated by Django 4.0.3 on 2022-05-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_historialmensajes_fecha_historialmensajes_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmensajes',
            name='fecha',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='historialmensajes',
            name='hora',
            field=models.CharField(max_length=10),
        ),
    ]
