# Generated by Django 4.0.3 on 2022-05-05 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_lineaspedido_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineasCompuestas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linea_compuesta', models.IntegerField()),
                ('composicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.composicionteclas')),
                ('linea_pricipal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.lineaspedido')),
            ],
        ),
    ]
