# Generated by Django 5.2.7 on 2025-11-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_delete_sync_lineaspedido_id_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
