# Generated by Django 4.0.3 on 2022-05-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_lineascompuestas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineascompuestas',
            old_name='linea_pricipal',
            new_name='linea_principal',
        ),
        migrations.AlterField(
            model_name='lineaspedido',
            name='estado',
            field=models.CharField(choices=[('A', 'Anulado'), ('P', 'Pedido activo'), ('R', 'Regalo'), ('C', 'Linea cobrada'), ('M', 'Pertenece a promocion o grupo')], db_column='Estado', default='P', max_length=1),
        ),
    ]
