# Generated by Django 4.2.26 on 2025-12-01 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_dispositivo_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='esta_facturada',
            field=models.BooleanField(default=False, help_text='Indica si este ticket ha sido canjeado por una Factura Completa'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_expedicion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora exacta de expedición (Requisito VeriFactu)', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='numero_factura',
            field=models.CharField(default='', help_text='Número secuencial de la factura dentro de la serie', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='numero_serie',
            field=models.CharField(blank=True, default='', help_text='Serie de la factura (ej: 2024A)', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='prev_hash',
            field=models.CharField(blank=True, default='', help_text='Hash del ticket encadenado anterior (SHA-256)', max_length=64),
        ),
        migrations.AddField(
            model_name='ticket',
            name='qr_code',
            field=models.TextField(blank=True, default='', help_text='Cadena de texto completa contenida en el QR'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='qr_image',
            field=models.ImageField(blank=True, help_text='Imagen del código QR generado', null=True, upload_to='tickets/qr/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sent_to_aeat',
            field=models.BooleanField(default=False, help_text='Indica si el registro ha sido enviado exitosamente a la AEAT'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='signature',
            field=models.CharField(blank=True, default='', help_text='Huella o Hash del registro actual', max_length=64),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipo_factura',
            field=models.CharField(choices=[('F1', 'Factura Simplificada'), ('F2', 'Factura Completa'), ('R1', 'Factura Rectificativa')], default='F1', help_text='Tipo de factura según normativa', max_length=10),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre_razon', models.CharField(max_length=200)),
                ('nif', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('cp', models.CharField(max_length=10)),
                ('poblacion', models.CharField(max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_expedicion', models.DateTimeField(auto_now_add=True)),
                ('numero_serie', models.CharField(default='', max_length=20)),
                ('numero_factura', models.CharField(default='', max_length=50)),
                ('tipo_factura', models.CharField(default='F2', max_length=10)),
                ('prev_hash', models.CharField(blank=True, default='', max_length=64)),
                ('signature', models.CharField(blank=True, default='', max_length=64)),
                ('qr_code', models.TextField(blank=True, default='')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='facturas/qr/')),
                ('sent_to_aeat', models.BooleanField(default=False)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='gestion.ticket')),
            ],
            options={
                'db_table': 'facturas',
            },
        ),
    ]
