# Generated by Django 4.2.26 on 2025-12-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_ticket_esta_facturada_ticket_fecha_expedicion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='qr_image',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='qr_image',
        ),
        migrations.AddField(
            model_name='factura',
            name='xml_firmado',
            field=models.TextField(blank=True, help_text='XML firmado generado para VeriFactu', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='xml_firmado',
            field=models.TextField(blank=True, help_text='XML firmado generado para VeriFactu', null=True),
        ),
    ]
